### ISSUE TITLE
Depreciated vs. Deprecated

### ISSUE THREAD

**Issue by kenlyon** [mattwright324/pdn-plugin-index#3]
This is a non-functional issue, more of a language nit-pick but I'll mention it anyway...

In the Search Options, the Plugin Type list has the entry "Depreciated". I believe it should be "Deprecated". When something is said to have depreciated (like a car) it has decreased in monetary value, whereas something that is deprecated should not to be used any more.

There is a fair bit of discussion on this topic in various places.

**Comment by Sigillatus** [comment]
Hello Ken,

Thanks for your thoughts on this. I agree with you.

![image](https://user-images.githubusercontent.com/14228355/63204013-a3d2f280-c0e7-11e9-837e-f891abb199a6.png)

![image](https://user-images.githubusercontent.com/14228355/63204018-b4836880-c0e7-11e9-877d-c0a0b254ad45.png)

I used the term "depreciated", because I believed users of the Plugin Index would understand that term. Deprecated is a term not widely used outside technical circles. Yes I'm a fan of language and its correct use (grammar-ogre too), but I'm not a professional wordsmith. 

I will consider making this change. I doubt many users will actually notice!

Thanks again for bringing this to our attention.

**Comment by mattwright324** [comment]
I will agree to this too.

My decision to have `Depreciated` as a selected by default option in the application was because that naming sounded like it still had some worth but less so. Deprecated is a common term as a dev, and changing that naming would make me rethink that decision. Assuming `Deprecated` is the more appropriate thing to call it, I would additionally want to not make it a default selected status.

**Comment by Sigillatus** [comment]
I'll upload a changed json file at the end of ths month, along with my scheduled monthly update. At the same time I'll change **depreciated** to **deprecated** and change its default to unchecked.

**Comment by Sigillatus** [comment]
...or I'll do it right now.  😉

**Comment by Sigillatus** [comment]
Done!

**Comment by mattwright324** [comment]
Neat, before closing the issue then, should it be capitalized in the data too? Currently it's showing as fully-lowercase on the plugin tags which is different from the other statuses.

**Comment by Sigillatus** [comment]
Quite right.

I did a search & replace on the entire VS solution to hack this change out. I'll upload the new JSON at the end of the month (I was too rushed to go through the entire update process).

**Comment by mattwright324** [comment]
I made the quick fix with search and replace in the json file so the issue can be closed, you will still need to update the data so it stays that way when making the next update.
